### ISSUE TITLE
官方master分支下更新到最新版本后仍然不能显示用户也不显示访问记录！！

### ISSUE THREAD

**Issue by zxlhhyccc** [destan19/OpenAppFilter#102]
已经5、6个小时了。。。。
![image](https://user-images.githubusercontent.com/45259624/111899495-e5681400-8a67-11eb-86ef-f81d22f1a4ed.png)

**Comment by keeno1982** [comment]
什么时候能修复呢？

**Comment by zxlhhyccc** [comment]
> 什么时候能修复呢？

只有等dalao修复了，我菜鸟。。。。

**Comment by zxlhhyccc** [comment]
已经快两天了，还是没显示用户和访问记录：
![image](https://user-images.githubusercontent.com/45259624/112026393-1e3fe000-8b71-11eb-8f00-86b92f375991.png)

**Comment by lxwq** [comment]
![image](https://user-images.githubusercontent.com/51162826/112072920-dee3b480-8bad-11eb-9762-87f9e535d56e.png)
为什么我用官方master分支编译后打不开,出这个错误

**Comment by zxlhhyccc** [comment]
> ![image](https://user-images.githubusercontent.com/51162826/112072920-dee3b480-8bad-11eb-9762-87f9e535d56e.png)
> 为什么我用官方master分支编译后打不开,出这个错误

oaf是稳定版还是最新版？稳定版的luci有个bug，将~=修改我==就可以了。。。你看一下我发的issue

**Comment by keeno1982** [comment]
@zxlhhyccc 你那边可以显示用户了吗？

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 你那边可以显示用户了吗？

不能。。。。

**Comment by secretandanon** [comment]
看这个 https://github.com/destan19/OpenAppFilter/issues/112
