### ISSUE TITLE
运行环境检测失败，请先关闭ACC加速模块!

### ISSUE THREAD

**Issue by xiaoqi2020** [destan19/OpenAppFilter#105]
实际上并没有使用ACC加速模块，编译固件的时候也没有选择加速模块
![image](https://user-images.githubusercontent.com/50669177/112777669-59f90f00-9075-11eb-9f04-06358e9434cd.png)

**Comment by xylz0928** [comment]
同样问题

**Comment by zxlhhyccc** [comment]
> 实际上并没有使用ACC加速模块，编译固件的时候也没有选择加速模块
> ![image](https://user-images.githubusercontent.com/50669177/112777669-59f90f00-9075-11eb-9f04-06358e9434cd.png)

默认肯定是加速模块已编译。。。

**Comment by xiaoqi2020** [comment]
> > 实际上并没有使用ACC加速模块，编译固件的时候也没有选择加速模块
> > ![image](https://user-images.githubusercontent.com/50669177/112777669-59f90f00-9075-11eb-9f04-06358e9434cd.png)
> 
> 默认肯定是加速模块已编译。。。

自己编译的固件，有没有勾选ACC加速模块自己心里还是清楚的，你如果一致认为插件没问题，不可能出现BUG的话，我也没办法！

**Comment by xiaoqi2020** [comment]
> > 实际上并没有使用ACC加速模块，编译固件的时候也没有选择加速模块
> > ![image](https://user-images.githubusercontent.com/50669177/112777669-59f90f00-9075-11eb-9f04-06358e9434cd.png)
> 
> 默认肯定是加速模块已编译。。。
所有插件都在这了，
![image](https://user-images.githubusercontent.com/50669177/113146769-a7869f00-9262-11eb-96d3-436ea3509918.png)
![image](https://user-images.githubusercontent.com/50669177/113146803-b1a89d80-9262-11eb-9b50-898802655c55.png)

**Comment by destan19** [comment]
防火墙fullcone-nat需要关闭

**Comment by xiaoqi2020** [comment]
> 防火墙fullcone-nat需要关闭

Ok了，谢谢，关闭fullcone-nat后有没有什么别的影响？

**Comment by secretandanon** [comment]
目测没有
