### ISSUE TITLE
请问dalao，什么时候能适配比如官方的master分支？！

### ISSUE THREAD

**Issue by zxlhhyccc** [destan19/OpenAppFilter#114]
目前过滤在官方master分支下，包括：用户等均无法显示！

![image](https://user-images.githubusercontent.com/45259624/114746321-2eb73500-9d82-11eb-95e8-ecc860b1d845.png)

**Comment by muziling** [comment]
dmesg里有这个错误：[99490.503072] mac format error: :
代码里可以加一些调试日志吗？
