### ISSUE TITLE
对我的世界没有效果

### ISSUE THREAD

**Issue by bwsnb** [destan19/OpenAppFilter#117]
我测试了《我的世界》网易版，不能有效屏蔽。无奈只能设置本地防火墙了。

**Comment by destan19** [comment]
应该可以的啊，安卓还是ios

**Comment by bwsnb** [comment]
电脑版的

**Comment by bwsnb** [comment]
昨天抓了游戏启动的时候访问的域名，用passwall做了规则，现在打开游戏就提示服务器升级， 也算解决了。
