### ISSUE TITLE
使用openwrt-21.02编译报错

### ISSUE THREAD

**Issue by kexix** [destan19/OpenAppFilter#119]
在OpenWrt-21.02B单独编译插件时报错，但是如果编译进固件里，又不报错，但是实际编译进去没有，能不能使用还不知道。
编译环境在CentOS8.3和Ubuntu20.04下都没能成功，以下是报错内容（个人初步怀疑是依赖问题）
make[1]: Entering directory '/Dan/openwrt'
make[1]: *** No rule to make target 'package/OpenAppFilter/compile'.  Stop.
make[1]: Leaving directory '/Dan/openwrt'
make: *** [/Dan/openwrt/include/toplevel.mk:230: package/OpenAppFilter/compile] Error 2

**Comment by wlshdjj** [comment]
以前没成功编译过的模块不能单独编译。

**Comment by wlshdjj** [comment]
以前没成功编译过的模块不能单独编译。

**Comment by wlshdjj** [comment]
以前没成功编译过的模块不能单独编译。
