### ISSUE TITLE
特征库内容修改无法生效

### ISSUE THREAD

**Issue by hdydy** [destan19/OpenAppFilter#12]
特征库配置文件: ` /etc/appfilter/feature.cfg`

---
修改此文件无法生效。经测试：
1. 将苏宁易购的规则写入抖音（抖音规则已经删除）的一栏中，打开抖音过滤按钮无法过滤苏宁易购，但是打开苏宁易购过滤按钮可正常过滤。
2. 在feature.cfg中增加新栏目会被添加进.class并在web上展出，但是其中的过滤规则无法生效。
3. `/etc/init.d/appfilter restart`与重启均已尝试，以上两个问题均依旧存在。
---

结论：
feature.cfg文件的确被读取，但其只能用作添加.class以在web展示复选框，其中的过滤规则并未被读取，可能被存在了其他位置（重启无效说明不是存在内存），而非`/etc/appfilter/feature.cfg`。目前通过修改feature.cfg文件没有办法修改过滤规则。

**Comment by destan19** [comment]
苏宁易购已经在购物中存在了的，可能已经识别成购物中的那个id
