### ISSUE TITLE
使用在旁路由中无法不能获取用户信息，没有任何用户和访问记录，但是能对全局生效。

### ISSUE THREAD

**Issue by qianfendou** [destan19/OpenAppFilter#122]
主路由将网关和DNS指向旁路由，主路由开启DHCP，大部分设备在主路由中指定静态地址，旁路由（J1900）关闭DHCP，ARP能获取获取链接的用户。

**Comment by tingyue-wu** [comment]
mac过滤，时间控制插件，在旁路由中无效，这个能对全局有效，也是关闭去广告、科学上网分流、硬件加速的结果吗？鱼和熊掌不可得兼。
