### ISSUE TITLE
能不能和op内核同步发布oaf插件版本呀

### ISSUE THREAD

**Issue by lijinlong2baby** [destan19/OpenAppFilter#123]
使用5.4.113内核安装105版本插件 用户列表是空的，好像是appfilter5.0的问题。
![微信截图_20210511105417](https://user-images.githubusercontent.com/47732238/117751703-1f73bc00-b248-11eb-9745-f72deec147ec.png)

**Comment by zxlhhyccc** [comment]
早就是这样了，所以我现在还是使用3.0版本

**Comment by destan19** [comment]
没有安装成功内核模块，直接升级固件
