### ISSUE TITLE
抖音直播

### ISSUE THREAD

**Issue by 355620911** [destan19/OpenAppFilter#124]
抖音短视频和抖音直播可以分开屏蔽吗？我老婆看抖音直播购物我都快疯了…感谢

**Comment by keeno1982** [comment]
勇气可嘉

**Comment by destan19** [comment]
应该是可以的，不怕跪榴莲么

**Comment by 355620911** [comment]
> 
> 
> 应该是可以的，不怕跪榴莲么

跪榴莲没什么，主要是能省钱·····直播带货的太能忽悠了

**Comment by 0neday** [comment]
`address=/douyincdn.com/0.0.0.0`
just block douyin zhibo

**Comment by tingyue-wu** [comment]
用流量看，不是更花钱？
