### ISSUE TITLE
过滤记录app名称和实际的不匹配

### ISSUE THREAD

**Issue by anai1943** [destan19/OpenAppFilter#131]
首先感谢作者的辛苦开发，反馈个bug。redmi ac 2100，刷的 openwrt-ramips-mt7621-xiaomi_redmi-router-ac2100-squashfs-sysupgrade-oaf5.0.1-2021-3-31.bin 固件，
玩pc版英雄联盟游戏时，过滤记录内记录的是如下数据，设置过滤后可以正常过滤，只是app名称和实际的不匹配

App | 主机名 | mac地址 | 开始时间 | 访问时长 | 过滤状态
-- | -- | -- | -- | -- | --
和平精英 | DESKTOP-M5SNKxx | b4:2e:99:67:3b:xx | 2021/06/15 17:26:04 | - | 已过滤
和平精英 | DESKTOP-M5SNKxx | b4:2e:99:67:3b:xx | 2021/06/14 07:52:53 | 3小时7分 | 未过滤
QQ飞车 | DESKTOP-M5SNKxx | b4:2e:99:67:3b:xx | 2021/06/14 08:36:55 | 2小时23分 | 未过滤

规则
2002 和平精英:[tcp;;;;;00:43|1:66|02:aa,tcp;;;;;00:33|1:66|03:0a|05:0a|,tcp;;;;;00:01|1:00|02:00,udp;;;;;00:59|01:ad|03:45|05:e4,udp;;;;;00:b9|01:5d|03:39|05:77]
2003 英雄联盟:[udp;;;;;44:00|45:00|46:00|47:02]
2015 我的世界:[tcp;;443;g79mclobt.nie.netease;;]
2004 荒野行动:[udp;;;;;00:05|01:09,tcp;;;;;00:02|01:00|02:00|03:00]
2005 欢乐斗地主:[tcp;;8000;;;00:74|01:67|02:77|03:5f]
2006 梦幻西游:[tcp;;;;;00:0e|01:00|02:fe|03:ff]
2007 明日之后:[udp;;;;;00:05|01:09|02:00,tcp;;;;;00:02|01:00|02:00|03:00|04:00|05:00] 
2008 QQ飞车:[udp;;;;;00:28|01:28,tcp;;10000;;;00:33|01:66|02:00|03:08]

**Comment by destan19** [comment]
很多app有公共特征，不处理
