### ISSUE TITLE
请问OpenAppFilter是否支持旁路由的docker上运行

### ISSUE THREAD

**Issue by rilyuuj** [destan19/OpenAppFilter#137]
目前旁路由为一个armbian盒子，openwrt为docker版本并运行oaf等应用。
家用部分设备通过http/sock5 代理进行海外或者国内访问。
请问这样的模型能否获取客户端的应用流量审计呢？

有没有大佬是类似的拓扑，麻烦分享下。

另外请问编译好oaf之后菜单里为啥只有一个基本设置？

**Comment by tingyue-wu** [comment]
应该不行。我也是这样的配置，旁路由上时间控制插件和mac过滤插件都失效来着。

**Comment by ZqinKing** [comment]
肯定是不行的，kod驱动在docker里没法用
