### ISSUE TITLE
能加入 和平精英不？吃鸡

### ISSUE THREAD

**Issue by JSZMonkey** [destan19/OpenAppFilter#150]
能加入 和平精英不？吃鸡

**Comment by ibibii** [comment]
这个有没有

**Comment by LiYang15954317975** [comment]
大哥能教一下怎么安装ipk吗 我是小白
![image](https://user-images.githubusercontent.com/99418812/194766761-35b2eed9-f754-4bdb-8bae-5f0e7774b855.png)
