### ISSUE TITLE
编译时报错

### ISSUE THREAD

**Issue by YasinQAQ** [destan19/OpenAppFilter#157]
`make[4]: Entering directory '/home/user/openwrt/gl-infra-builder/wlan-ap/openwrt/build_dir/target-arm_cortex-a7_musl_eabi/linux-ipq807x_ipq60xx/linux-5.4.164-qsdk-d5fcb18e5420670c8734c6a659873e73adab6dac'
  CC [M]  /home/user/openwrt/gl-infra-builder/wlan-ap/openwrt/build_dir/target-arm_cortex-a7_musl_eabi/linux-ipq807x_ipq60xx/oaf/app_filter.o
/home/user/openwrt/gl-infra-builder/wlan-ap/openwrt/build_dir/target-arm_cortex-a7_musl_eabi/linux-ipq807x_ipq60xx/oaf/app_filter.c: In function 'af_send_msg_to_user':
/home/user/openwrt/gl-infra-builder/wlan-ap/openwrt/build_dir/target-arm_cortex-a7_musl_eabi/linux-ipq807x_ipq60xx/oaf/app_filter.c:964:1: error: the frame size of 1032 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]
}
^
cc1: all warnings being treated as errors
make[5]: *** [scripts/Makefile.build:297: /home/user/openwrt/gl-infra-builder/wlan-ap/openwrt/build_dir/target-arm_cortex-a7_musl_eabi/linux-ipq807x_ipq60xx/oaf/app_filter.o] Error 1
make[4]: *** [Makefile:1734: /home/user/openwrt/gl-infra-builder/wlan-ap/openwrt/build_dir/target-arm_cortex-a7_musl_eabi/linux-ipq807x_ipq60xx/oaf] Error 2
make[4]: Leaving directory '/home/user/openwrt/gl-infra-builder/wlan-ap/openwrt/build_dir/target-arm_cortex-a7_musl_eabi/linux-ipq807x_ipq60xx/linux-5.4.164-qsdk-d5fcb18e5420670c8734c6a659873e73adab6dac'
make[3]: *** [Makefile:41: /home/user/openwrt/gl-infra-builder/wlan-ap/openwrt/build_dir/target-arm_cortex-a7_musl_eabi/linux-ipq807x_ipq60xx/oaf/.built] Error 2
make[3]: Leaving directory '/home/user/openwrt/gl-infra-builder/feeds/custom/oaf'
time: package/feeds/custom/oaf/compile#1.45#0.36#2.13
    ERROR: package/feeds/custom/oaf failed to build.
make[2]: *** [package/Makefile:116: package/feeds/custom/oaf/compile] Error 1
make[2]: Leaving directory '/home/user/openwrt/gl-infra-builder/wlan-ap/openwrt'
make[1]: *** [package/Makefile:110: /home/user/openwrt/gl-infra-builder/wlan-ap/openwrt/staging_dir/target-arm_cortex-a7_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/user/openwrt/gl-infra-builder/wlan-ap/openwrt'
make: *** [/home/user/openwrt/gl-infra-builder/wlan-ap/openwrt/include/toplevel.mk:230: world] Error 2`

**Comment by destan19** [comment]
用的哪套代码编译的
