### ISSUE TITLE
x86 5.18内核编译出错

### ISSUE THREAD

**Issue by xiangfeidexiaohuo** [destan19/OpenAppFilter#158]
Lean的源码，x86  5.18内核

make[3]: Entering directory '/home/cheche/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.18.10'
  CC [M]  /home/cheche/lede/build_dir/target-x86_64_musl/linux-x86_64/oaf/app_filter.o
/home/cheche/lede/build_dir/target-x86_64_musl/linux-x86_64/oaf/app_filter.c: In function 'load_feature_buf_from_file':
/home/cheche/lede/build_dir/target-x86_64_musl/linux-x86_64/oaf/app_filter.c:237:3: error: unknown type name 'mm_segment_t'; did you mean 'mm_context_t'?
   mm_segment_t fs;
   ^~~~~~~~~~~~
   mm_context_t
/home/cheche/lede/build_dir/target-x86_64_musl/linux-x86_64/oaf/app_filter.c:237:16: warning: unused variable 'fs' [-Wunused-variable]
   mm_segment_t fs;
                ^~
make[4]: *** [scripts/Makefile.build:288: /home/cheche/lede/build_dir/target-x86_64_musl/linux-x86_64/oaf/app_filter.o] Error 1

修改app_filter.c:这个文件，干掉mm_segment_t fs;这行后，5.18内核下编译没问题了。
![image](https://user-images.githubusercontent.com/32566723/178311107-f18dfbd5-ece3-4256-8fbc-7d1166cec5c9.png)

**Comment by makebl** [comment]
一样的 报错
