### ISSUE TITLE
不显示连接设备

### ISSUE THREAD

**Issue by rq1025330** [destan19/OpenAppFilter#164]
![image](https://user-images.githubusercontent.com/52870887/192535667-d1d861e0-d498-4f67-98e6-78ae3ed6c8fe.png)

**Comment by rq1025330** [comment]
这是什么原因呢 一直这个界面

**Comment by ktkiss** [comment]
我也一样

**Comment by rq1025330** [comment]
我是主路由，交换机扩口

**Comment by ktkiss** [comment]
> 我是主路由，交换机扩口

也不知道是什么问题

**Comment by rq1025330** [comment]
> > 我是主路由，扩口
> 
> 也不知道是什么问题

你解决了吗？

**Comment by Yinghai75** [comment]
我也是这样，openwrt里的工具软件坑真多，这个应用过滤类的，我到现在没遇到一款能用的...
