### ISSUE TITLE
通过https://supes.top/编译的章鱼星球固件，一直提示“正在收集数据…”

### ISSUE THREAD

**Issue by vipnetant** [destan19/OpenAppFilter#167]
![image](https://user-images.githubusercontent.com/3382577/196847078-8babfdc4-c8d3-4091-b03d-8f2036d9549f.png)
`luci-app-adguardhome luci-app-netdata luci-app-netspeedtest luci-app-ttyd luci-app-store luci-app-oaf luci-app-serverchan`
adg home和其他可能冲突的都关了，还是这样。

**Comment by destan19** [comment]
你复位后试试，不行的话看看kmod-oaf模块有没有编译进去

**Comment by vipnetant** [comment]
使用的是在线编译，这已经是新安装的，所以不用复位。
![image](https://user-images.githubusercontent.com/3382577/209421745-7392baca-bf41-432f-9300-34be3539a7da.png)
