### ISSUE TITLE
无法加载访问记录

### ISSUE THREAD

**Issue by tubimasky** [destan19/OpenAppFilter#17]
编译自 Mleaf 的 openwrt https://github.com/Mleaf/openwrt
在package 目录放了这个项目编译
![image](https://user-images.githubusercontent.com/13502844/74131840-392aeb80-4c20-11ea-81ef-2f4d0993c9f6.png)

http://192.168.1.1/cgi-bin/luci/admin/network/user_status?1581321549979
Failed to execute call dispatcher target for entry '/admin/network/user_status'.
The called action terminated with an exception:
/usr/lib/lua/luci/controller/appfilter.lua:56: module 'luci.tools.status' not found:
	no field package.preload['luci.tools.status']
	no file './luci/tools/status.lua'
	no file '/usr/share/lua/luci/tools/status.lua'
	no file '/usr/share/lua/luci/tools/status/init.lua'
	no file '/usr/lib/lua/luci/tools/status.lua'
	no file '/usr/lib/lua/luci/tools/status/init.lua'
	no file './luci/tools/status.so'
	no file '/usr/lib/lua/luci/tools/status.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/controller/appfilter.lua:56: in function </usr/lib/lua/luci/controller/appfilter.lua:55>
	(tail call): ?

**Comment by springsunx** [comment]
在开发板上编译可以通过，同样是无法加载记录。

**Comment by destan19** [comment]
页面显示问题，你可以用OpenWrt18.06、OpenWrt19.07上编译试试，目前只在原生的OpenWrt测试

**Comment by kang-mk** [comment]
我的也是这样的
OpenWrt 19.07-SNAPSHOT / LuCI 18-Lienol (git-20.064.57202-0bbab99)

**Comment by kang-mk** [comment]
希望可以修复下
