### ISSUE TITLE
Linksys E8450 (UBI)可以安装吗

### ISSUE THREAD

**Issue by wangpengju00** [destan19/OpenAppFilter#170]
ARMv8 Processor rev 4
mt7622
OpenWrt 22.03.2 r19803-9a599fee93 / LuCI openwrt-22.03 branch git-22.304.65171-ec905e6
内核版本 | 5.10.146

我试了一下直接安装项目里的ipkstore，可以安装，但是打开乱码
我该怎么安装
谢谢了

**Comment by wangpengju00** [comment]
openwrt原生系统

**Comment by destan19** [comment]
要自己编译或者下载已经集成好的固件
