### ISSUE TITLE
目前源码通过直接加入编译，是否支持master分支？！

### ISSUE THREAD

**Issue by zxlhhyccc** [destan19/OpenAppFilter#171]
RT。。。。

**Comment by destan19** [comment]
master要等后面适配

**Comment by zxlhhyccc** [comment]
> master要等后面适配

请问大佬，大概什么时候可以适配呢？我都等了N年了。。。。

**Comment by destan19** [comment]
最新的提交已经可以了，可以直接安装在master 22.03

**Comment by zxlhhyccc** [comment]
> 最新的提交已经可以了，可以直接安装在master 22.03

最新的版本支持了22.03吗？

**Comment by sbwml** [comment]
22.03 不是一直都可以工作吗？ 22.03-rc1 到目前的22.03.2  我都一直在使用

**Comment by sbwml** [comment]
效果挺良好的还，立竿见影
![1](https://user-images.githubusercontent.com/16485166/209040942-ca396383-a422-4dfb-8adf-28ad5f43916e.png)
![2](https://user-images.githubusercontent.com/16485166/209041002-c389ab73-c52e-43ec-bb1d-b7c31f462a74.png)
