### ISSUE TITLE
官方源码可以添加编译，但是运行没有效果，任何设备都无法过滤，希望支持下官方源码，谢谢大佬！

### ISSUE THREAD

**Issue by snakwu** [destan19/OpenAppFilter#173]
官方源码可以添加编译，但是运行没有效果，任何设备都无法过滤，希望支持下官方源码，谢谢大佬！

**Comment by destan19** [comment]
直接下载openwrt官方的22.03固件，然后安装插件试试，过滤是没问题的

**Comment by snakwu** [comment]
> 直接下载openwrt官方的22.03固件，然后安装插件试试，过滤是没问题的

因为我个人需要，需要用到编译固件的，可以修复一下支持官方源码编译吗？谢谢大佬的回复！

**Comment by TempleZhou** [comment]
直接用的官方22.03固件，插件装上了没问题，统计app时间也没问题，就是过滤不行。。。。

**Comment by TempleZhou** [comment]
> 

关了 v2ray 也过滤不了

**Comment by destan19** [comment]
> 

你说的官方的固件是哪个？https://openwrt.org/下载的才是官方，官方固件没有v2ray啊，官方固件应该是没有问题的，检查下有没有开启其他插件，最好在恢复出厂状态测试

**Comment by destan19** [comment]
> 

你说的官方的固件是哪个？https://openwrt.org/下载的才是官方，官方固件没有v2ray啊，官方固件应该是没有问题的，检查下有没有开启其他插件，最好在恢复出厂状态测试

**Comment by wzming** [comment]
随同官方openwrt源码(非lede源码)一起编译进固件，发现也是过滤不了，统计的数据是没有问题的，统计的数据里面也能识别出来应用是哪个，就是无法过滤。
