### ISSUE TITLE
Openwrt Nightly Build

### ISSUE THREAD

**Issue by tango38317** [destan19/OpenAppFilter#179]
Hello @destan19  ,
i tried to add OAF to my build system (Openwrt Snapshot) and tried to build a nightly build with OAF, but build is not successful.
i receive a view error attached to log.
maybe you have some hints how to solve this issue
many thanks
Chris
[oaf.txt](https://github.com/destan19/OpenAppFilter/files/11477767/oaf.txt)

**Comment by wzming** [comment]
![image](https://github.com/destan19/OpenAppFilter/assets/3351908/90ba08c3-b617-4dab-9049-5714c600fb21)

同样的问题，openwrt master分支，oaf master分支，WSL2-UBUNTU

**Comment by destan19** [comment]
Hello tango
It is because some kernel compilations have enabled strict compilation mode, causing warnings to be treated as errors, and relevant warnings have been ignored or fixed.
thanks for feedback.
