### ISSUE TITLE
付费版OAF库也就加了100条数据，收费39？？

### ISSUE THREAD

**Issue by xufengnian** [destan19/OpenAppFilter#186]
离谱，开源版OAF里有300+条数据，花了39元买专业版也只有400+条，而且其中300条是开源版的数据？？这不纯纯坑人？？

**Comment by destan19** [comment]
你可以自己去提取100条数据试试，一个app我只算10分钟，39不值，觉得开源太多没问题啊，那后面删掉开源特征库就可以了
