### ISSUE TITLE
有适配X86内核4.14.115版本的吗？4.14.99貌似不能安装kmod-oaf ipk

### ISSUE THREAD

**Issue by qianfendou** [destan19/OpenAppFilter#2]
有适配X86内核4.14.115版本的吗？4.14.99貌似不能安装kmod-oaf ipk?

**Comment by destan19** [comment]
版本的问题， 你可以下载openwrt对应的版本，然后加入OpenAppFilter package进行编译

**Comment by vircloud** [comment]
有没有可能在 README 说明匹配哪个内核版本？
我用 [19.07.1 SDK](https://downloads.openwrt.org/releases/19.07.1/targets/x86/generic/openwrt-sdk-19.07.1-x86-generic_gcc-7.5.0_musl.Linux-x86_64.tar.xz) 编译出来的限制内核版本是 **4.14.167-1-a1300ca9e381f341b39d355566868f0c**，但是官方放出的编译好的 [19.07.1 固件](https://downloads.openwrt.org/releases/19.07.1/targets/x86/generic/openwrt-19.07.1-x86-generic-combined-ext4.img.gz)的内核是 **4.19.101-1-f2c57a4079c1d2a25ef373f71a66a4de**，不知道是我操作问题，还是 oaf 本身有限制。

**Comment by destan19** [comment]
不建议用插件方式安装，基本很难匹配到对应内核和配置，除非在自己固件源码中编译
