### ISSUE TITLE
内核日志里出现大量记录，可以屏蔽吗？

### ISSUE THREAD

**Issue by Fyred** [destan19/OpenAppFilter#22]
应该是appfilter产生的吧？不启动appfilter的话，也会反复产生，求解决，谢谢！

[ 9852.383899] __af_update_client_app_info 727 visit_app_num = 0
[ 9852.389775] [5] 192.168.50.100 visit 7001, time=1583002817 action=Accept, 0/32
[ 9852.397256] __af_update_client_app_info 727 visit_app_num = 0
[ 9852.403156] [5] 192.168.50.100 visit 7001, time=1583002817 action=Accept, 0/33
[ 9852.410626] __af_update_client_app_info 727 visit_app_num = 0
[ 9852.416508] [5] 192.168.50.100 visit 7001, time=1583002817 action=Accept, 0/34
[ 9852.424029] __af_update_client_app_info 727 visit_app_num = 0
[ 9852.429956] [5] 192.168.50.100 visit 7001, time=1583002817 action=Accept, 0/35
[ 9852.437506] __af_update_client_app_info 727 visit_app_num = 0
[ 9852.443458] [5] 192.168.50.100 visit 7001, time=1583002817 action=Accept, 0/36
[ 9882.383305] __af_update_client_app_info 727 visit_app_num = 0
[ 9882.389484] [5] 192.168.50.100 visit 7001, time=1583002847 action=Accept, 0/37
[ 9882.452149] __af_update_client_app_info 727 visit_app_num = 0
[ 9882.458319] [5] 192.168.50.100 visit 7001, time=1583002847 action=Accept, 0/38
[ 9882.466736] __af_update_client_app_info 727 visit_app_num = 0
[ 9882.472657] [5] 192.168.50.100 visit 7001, time=1583002847 action=Accept, 0/39
[ 9882.747383] __af_update_client_app_info 727 visit_app_num = 0
[ 9882.753566] [5] 192.168.50.100 visit 7001, time=1583002847 action=Accept, 0/40
[ 9883.034815] __af_update_client_app_info 727 visit_app_num = 0
[ 9883.040998] [5] 192.168.50.100 visit 7001, time=1583002848 action=Accept, 0/41
[ 9883.323861] __af_update_client_app_info 727 visit_app_num = 0
[ 9883.329853] [5] 192.168.50.100 visit 7001, time=1583002848 action=Accept, 0/42
[ 9883.612706] __af_update_client_app_info 727 visit_app_num = 0
[ 9883.621864] [5] 192.168.50.100 visit 7001, time=1583002848 action=Accept, 0/43
[ 9883.689156] __af_update_client_app_info 727 visit_app_num = 0
[ 9883.695301] [5] 192.168.50.100 visit 7001, time=1583002848 action=Accept, 0/44
[ 9907.161164] __af_update_client_app_info 727 visit_app_num = 0
[ 9907.167303] [0] 192.168.50.115 visit 1002, time=1583002872 action=Accept, 0/25
[ 9907.565985] __af_update_client_app_info 727 visit_app_num = 0
[ 9907.572188] [0] 192.168.50.115 visit 1002, time=1583002872 action=Accept, 0/26
[ 9908.346208] __af_update_client_app_info 727 visit_app_num = 0
[ 9908.352461] [0] 192.168.50.115 visit 1002, time=1583002873 action=Accept, 0/27
[ 9941.725422] __af_update_client_app_info 727 visit_app_num = 0
[ 9941.731671] [5] 192.168.50.100 visit 7001, time=1583002906 action=Accept, 0/45
[ 9942.765276] __af_update_client_app_info 727 visit_app_num = 0
[ 9942.771467] [5] 192.168.50.100 visit 7001, time=1583002907 action=Accept, 0/46
[ 9944.011373] __af_update_client_app_info 727 visit_app_num = 0
[ 9944.017578] [5] 192.168.50.100 visit 7001, time=1583002909 action=Accept, 0/47
[ 9961.681687] __af_update_client_app_info 727 visit_app_num = 0
[ 9961.687886] [5] 192.168.50.100 visit 7001, time=1583002926 action=Accept, 0/48
[ 9964.696128] __af_update_client_app_info 727 visit_app_num = 0
[ 9964.702286] [5] 192.168.50.100 visit 7001, time=1583002929 action=Accept, 0/49
[ 9969.701657] __af_update_client_app_info 727 visit_app_num = 0
[ 9969.707811] [5] 192.168.50.100 visit 7001, time=1583002934 action=Accept, 0/50
[ 9970.766724] __af_update_client_app_info 727 visit_app_num = 0
[ 9970.772872] [5] 192.168.50.100 visit 7001, time=1583002935 action=Accept, 0/51
[ 9971.060539] __af_update_client_app_info 727 visit_app_num = 0
[ 9971.066506] [5] 192.168.50.100 visit 7001, time=1583002936 action=Accept, 0/52

**Comment by destan19** [comment]
echo 0 >/proc/sys/oaf/debug  或者用最新的代码编译
