### ISSUE TITLE
在openwrt-master 5.4内核下不工作

### ISSUE THREAD

**Issue by QiuSimons** [destan19/OpenAppFilter#24]
![image](https://user-images.githubusercontent.com/45143996/75657994-62c8b700-5ca2-11ea-86da-fa80af1a7895.png)
makefile里面用到了一个过期的变量
然后即使修复变量问题之后，也不能在5.4内核上正确运行

**Comment by fbrav** [comment]
同样问题，n1一直显示 正在收集数据...
