### ISSUE TITLE
关于app特征库构建

### ISSUE THREAD

**Issue by Archiewyq** [destan19/OpenAppFilter#26]
hi,
想问一下，对于一个新app，如何构建对应的特征码呢？

**Comment by destan19** [comment]
/etc/appfilter/目录有个特征库文件，可以参考其他app的配置加入特征库，页面保存后会自动生成菜单

**Comment by Archiewyq** [comment]
ok，已搞明白了，多谢

**Comment by chinkiko** [comment]
add this to readme/wiki ?
