### ISSUE TITLE
QQ只是用TCP协议吗？

### ISSUE THREAD

**Issue by zhscnd** [destan19/OpenAppFilter#30]
我看QQ的过滤规则是这样的呢，都是TCP的，我看我的QQ登录用的是UDP协议
QQ:[tcp;;;;;00:02|-1:03,tcp;;;;;02:02|-1:03,tcp;;14000;;;,tcp;;8080;;;00:ca|01:3c,tcp;;;;;00:00|01:00|02:00|03:15]

QQ应该是开始会尝试用UDP登录，如果登录不成功再切换到TCP

**Comment by destan19** [comment]
是有udp的，后面再优化
