### ISSUE TITLE
在kernel 5.4下编译失败

### ISSUE THREAD

**Issue by garypang13** [destan19/OpenAppFilter#31]
用的是原版openwrt master分支,此版本kernel已升级至5.4,

报错 ERROR: module '/home/runner/work/Actions-OpenWrt-Snapshot/Actions-OpenWrt-Snapshot/openwrt/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/oaf.ko' is missing.

在kernel 4.19中一直编译正常.

**Comment by xmapst** [comment]
怎么解决??

**Comment by a-kibou** [comment]
出現一樣的問題，kmod-oaf套裝無法編譯，煩請解決。

**Comment by destan19** [comment]
近期会适配高版本内核

**Comment by lx521603** [comment]
同，lienol的dev-master分支竟然有这个包，打勾了就编译失败。

单独编译也不成功。

**Comment by garypang13** [comment]
已经适配 Kernel 5.4 了,感谢
