### ISSUE TITLE
为什么四个文件都编译好了 也都成功安装了 但是好像不起作用  一直在收集数据中

### ISSUE THREAD

**Issue by luuziiyoo** [destan19/OpenAppFilter#37]
主机名 | FriendlyWrt
主机型号 | FriendlyElec NanoPi R2S
CPU信息 | 1008 MHz 61.66°
固件版本 | OpenWrt R20.3.19 / LuCI Master (git-20.088.29068-cebe120) built by DYC

为什么四个文件都编译好了 也都成功安装了 但是好像不起作用  一直在收集数据中
<img width="1470" alt="截屏2020-04-07下午12 19 26" src="https://user-images.githubusercontent.com/10737650/78629647-39670080-78ca-11ea-9c18-98822f1aaf4b.png">

**Comment by 1049066154** [comment]
兼容问题,得用openwrt官方源码编译的固件

**Comment by luuziiyoo** [comment]
> 兼容问题，得用openwrt官方源码编译的固件

那废了 官方不支持r2s

**Comment by mengxd** [comment]
可以用lede代码编译，也可以正常使用，但前提是别打开网络加速Turbo ACC

**Comment by luuziiyoo** [comment]
> 可以用lede代码编译，也可以正常使用，但一定是别打开网络加速Turbo ACC

lede里貌似没有R2S刚进去看了看  没有3328的选择

**Comment by sonic0377** [comment]
> > 兼容问题，得用openwrt官方源码编译的固件
> 
> 那废了 官方不支持r2s

R2S已经有原生OP了

**Comment by zzhang1987** [comment]
https://github.com/destan19/OpenAppFilter/pull/52
This might help.
