### ISSUE TITLE
无法过滤抖音短视频

### ISSUE THREAD

**Issue by hdydy** [destan19/OpenAppFilter#4]
我用的这个[固件](https://github.com/coolsnowwolf/lede)，添加后编译成功也运行起来了。
但是我发现抖音并没有被过滤，大部分头像和评论图片以及视频预览图都屏蔽了，但是视频一个都没有屏蔽，希望更新一下视频过滤规则。

**Comment by destan19** [comment]
报下产品型号， 确定有没有其他加速模块

**Comment by hdydy** [comment]
x86架构，其他加速模块都关闭了也是过滤不了视频。

**Comment by destan19** [comment]
编译的时候三个模块都选择了吗， 其他的app可不可以过滤呢

**Comment by hdydy** [comment]
确定都编译了，微视和拼多多都屏蔽成功了。另外我发现一个小问题，打开后淘宝的图片加载缓慢，关掉后就正常了。

**Comment by hdydy** [comment]
新版更新后问题解决，可以正常屏蔽抖音了
