### ISSUE TITLE
APP访问时间问题

### ISSUE THREAD

**Issue by sonic0377** [destan19/OpenAppFilter#55]
![photo_2020-06-15_18-41-42](https://user-images.githubusercontent.com/54339314/84648700-f82d4580-af37-11ea-8b44-be905c318138.jpg)
APP访问记录的时间显示不正确，该怎么配置吗？

**Comment by sonic0377** [comment]
看到作者大佬答复过同样的问题了。。。。期待大佬早日适配新内核。

**Comment by destan19** [comment]
新版本没有该问题
