### ISSUE TITLE
最近的oaf在openwrt1806系列报错。

### ISSUE THREAD

**Issue by yaof2** [destan19/OpenAppFilter#58]
/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute cbi dispatcher target for entry '/admin/control/appfilter'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/appfilter/appfilter.lua:89: attempt to index local 't' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>

**Comment by wlshdjj** [comment]
对，是有这个问题。不要使用升级luci了。
