### ISSUE TITLE
disable sfe脚本是有问题的

### ISSUE THREAD

**Issue by wlshdjj** [destan19/OpenAppFilter#63]
if [ x"$enable" != x"1" ];then
		echo "appfilter is disabled"
		echo 0 >/proc/sys/oaf/enable>/dev/null
		uci set firewall.@defaults[0].flow_offloading=1
		return 0
    else
		insmod oaf >/dev/null
		echo 1 >/proc/sys/oaf/enable
		uci set firewall.@defaults[0].flow_offloading=0
	fi
首先，uci set只是在内存中修改，需要uci commit才是真正修改。修改之后还要reload一次才会使用新的配置（千万不要用restart）。
其次，这代码并没有检测人家原先是否启用，人家本来没有启用的，你关闭之后反而把人家的启用了，可能无意中造成了新的问题了。
最后，发现首次开机无法分配DHCP，因为之前没有这样的问题，我怀疑和这有关系。
我还是这样用好了：
    if [ x"$enable" != x"1" ];then
		echo "appfilter is disabled"
		echo 0 >/proc/sys/oaf/enable>/dev/null
#		uci set firewall.@defaults[0].flow_offloading=1 #管它呢
		return 0
    else
		insmod oaf >/dev/null
		echo 1 >/proc/sys/oaf/enable
		[ $(uci get firewall.@defaults[0].flow_offloading 2>/dev/null) == 1 ] && { uci set firewall.@defaults[0].flow_offloading=0 ; uci commit firewall ; /etc/init.d/firewall reload  >/dev/null 2>&1 ; } #如果人家本来就没有启用的就不要多此一举了，缩短开机时间。
	fi

**Comment by destan19** [comment]
加这几行代码关闭sfe确实有点别扭，之前主要考虑很多人反馈加速了不能用，但又不知道原因
后面还是去掉吧

**Comment by Archiewyq** [comment]
> 加这几行代码关闭sfe确实有点别扭，之前主要考虑很多人反馈加速了不能用，但又不知道原因
> 后面还是去掉吧

开了sfe或者qca-nss-ecm后，你在FORWARD上的hook就失效了(sfe的匹配在FORWARD之前，匹配到之后直接调dev_queue_xmit发送了)，我的解决办法是在sfe里再加一个hook专门处理经过sfe加速的流量。

**Comment by destan19** [comment]
sfe自行关闭，暂不支持同时开turbo acc和应用过滤
