### ISSUE TITLE
最新版无法过滤百度！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [destan19/OpenAppFilter#65]
![image](https://user-images.githubusercontent.com/45259624/94513627-ca9faa00-0251-11eb-93ac-8a83ec374d98.png)
![image](https://user-images.githubusercontent.com/45259624/94513648-d7240280-0251-11eb-87c1-d39610d7176e.png)

**Comment by destan19** [comment]
其他的网站如果可以的话，清下缓存
