### ISSUE TITLE
访问记录一直显示正在收集数据

### ISSUE THREAD

**Issue by lxwq** [destan19/OpenAppFilter#69]
访问记录一直显示正在收集数据
应用过滤也不起作用,
使用Lean的代码,luci-app-flowoffload,shortcut-fe,luci-app-sfe都没有编译,
选编安装的软件如图 
![image](https://user-images.githubusercontent.com/51162826/97947193-86ab4200-1dc7-11eb-81ef-15b0c2449607.png)

**Comment by destan19** [comment]
要检查下oaf内核模块是否已经加载和安装， 通过ssh后台 lsmod |grep oaf查看

**Comment by lxwq** [comment]
root@OpenWrt:~# lsmod |grep oaf
oaf                    49152  0
