### ISSUE TITLE
iOS QQ and QQi 国际版

### ISSUE THREAD

**Issue by chinkiko** [destan19/OpenAppFilter#75]
iOS QQ international v5 正常拦截
iOS QQ v8.4.9.604 无法拦截，正常收发消息，还能浏览看点和动态

另外 qq现在添加了“看点”“动态”的栏目，包含游戏视频推广等内容，是否可以添加规则阻拦/

**Comment by destan19** [comment]
目前只过滤qq登陆和聊天数据

**Comment by maxinhji19old** [comment]
现在国际版qq好像登录不上了
