### ISSUE TITLE
反馈一下,MT7621没有碰到过不断重启的问题。

### ISSUE THREAD

**Issue by syb999** [destan19/OpenAppFilter#8]
测试使用oaf版本  ：commit b9c82000824907e16a6ee3b9dee987ffa431d26b
使用OPENWRT Chaos_Calmer 3.18.109 
开启oaf过滤腾讯视频与斗鱼，测试过滤成功。设备一切正常。
测试使用设备newifi-d1,newifi-d2,hiwifi b70。
-------------------
该版本在19.07.0-rc1中，当接通互联网时，只要有wifi客户端接入，立刻造成路由器自动重启。
或是中继一个接通了互联网的无线信号。在成功连接后，路由器立刻进入无限重启的死循环。

**Comment by syb999** [comment]
老版本的oaf也同样正常使用。
bb 3.10内核下同样 使用正常。

**Comment by openwrt-diy** [comment]
OpenWrt-18.06.5 + luci-app-oaf-20191011  也是WAN接口插网线就重启的问题

**Comment by syb999** [comment]
对的，我测试不光是ramips，只要通internet,其他平台也是无限重启。

**Comment by wangwanggogo19xx** [comment]
也是遇到频繁重启的问题。。
