### ISSUE TITLE
在LEAN源码中编译，界面打开出错

### ISSUE THREAD

**Issue by dwj0** [destan19/OpenAppFilter#83]
你好， 我用 788c5c473277e6c9a21a74a44e72d1242139b665 这个提交的版本编译的固件，在网页中打不开界面，提示如下:
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute cbi dispatcher target for entry '/admin/network/appfilter'.
The called action terminated with an exception:
/usr/lib/lua/luci/util.lua:200: attempt to get length of local 'str' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

请教解决方法

**Comment by dwj0** [comment]
我把版本回退到上一个，可以正常打开

**Comment by tianiue** [comment]
编译不成功
