### ISSUE TITLE
快手和抖音过滤没效果

### ISSUE THREAD

**Issue by carrot117** [destan19/OpenAppFilter#86]
newifi3 d2，这里下载 https://www.right.com.cn/forum/thread-1481096-1-1.html 的L大openwrt，turbo acc，mwan3都没开，只开了openclash和adguardhome，ad是上游dns服务器，显示以过滤，实际上手机上还能正常播放视频
b站过滤没效果，王者有效果
请问是什么问题，需要提供什么日志

**Comment by pikachullk** [comment]
我使用openclash~如果是fake-ip好像也是没有效果的~

**Comment by carrot117** [comment]
> 我使用openclash~如果是fake-ip好像也是没有效果的~

我也是openclash啊，好像是软件本身的问题

**Comment by destan19** [comment]
自己排查原因，肯定是冲突或者安装问题
