### ISSUE TITLE
luci-app-oaf在官方master分支下页面出错！

### ISSUE THREAD

**Issue by zxlhhyccc** [destan19/OpenAppFilter#89]
![image](https://user-images.githubusercontent.com/45259624/106352203-fc1da480-631b-11eb-9889-087f795ddf37.png)

**Comment by zxlhhyccc** [comment]
经查，发现是更新了此段代码引起，删除正常。。。
![image](https://user-images.githubusercontent.com/45259624/106352336-3471b280-631d-11eb-9ef7-685f4f6bbe46.png)

**Comment by zxlhhyccc** [comment]
临时办法：
将if config_users~=nil then改为：if config_users==nil then即可，请dalao修复，谢谢！

**Comment by lxwq** [comment]
![image](https://user-images.githubusercontent.com/51162826/112102290-fc7f4100-8be2-11eb-9e4d-3faf1c462824.png)
和你上面的报错信息不一样的,我的好像是找不到文件,
在编译时也有错误信息,有几个文件找不到,

**Comment by lxwq** [comment]
![image](https://user-images.githubusercontent.com/51162826/112236001-b7a6e900-8c7a-11eb-93bf-c2d7d298193f.png)
编译时的错误信息,

**Comment by lxwq** [comment]
> ![image](https://user-images.githubusercontent.com/51162826/112236001-b7a6e900-8c7a-11eb-93bf-c2d7d298193f.png)
> 编译时的错误信息,

找到原因了,原来是因为luci-compat没有安装,编译上以后可以打开了,
但都是英文的,appfilter的主菜单也是英文,不知道还少什么东西没装,

**Comment by lxwq** [comment]
![image](https://user-images.githubusercontent.com/51162826/112600656-723a1580-8e4c-11eb-822b-152c11999741.png)
菜单是英文的,好像PO文件没起做用,这是怎么回事啊?
加了几个其它的软件包试了试,也是一样,
只有官方就在的软件包可以正常显示中文,

**Comment by d9394** [comment]
> 
> 
> 经查，发现是更新了此段代码引起，删除正常。。。
> ![image](https://user-images.githubusercontent.com/45259624/106352336-3471b280-631d-11eb-9ef7-685f4f6bbe46.png)

请问具体是修改哪个文件？
