### ISSUE TITLE
过滤不生效,正在收集数据...

### ISSUE THREAD

**Issue by lxwq** [destan19/OpenAppFilter#90]
[20210201.zip](https://github.com/destan19/OpenAppFilter/files/5909114/20210201.zip)
LEAN源码的配置文件,哪位大哥有空的话试试看,指正一下哪的问题,
![2021-02-02 14-17-43屏幕截图](https://user-images.githubusercontent.com/51162826/106560777-86efe080-6562-11eb-866f-82ae7758ba0b.png)
编译出来后就是这个样子,正在收集数据...
oaf是加载的,

root@OpenWrt:~# lsmod |grep oaf
oaf 49152 0

**Comment by zxlhhyccc** [comment]
> [20210201.zip](https://github.com/destan19/OpenAppFilter/files/5909114/20210201.zip)
> LEAN源码的配置文件,哪位大哥有空的话试试看,指正一下哪的问题,
> ![2021-02-02 14-17-43屏幕截图](https://user-images.githubusercontent.com/51162826/106560777-86efe080-6562-11eb-866f-82ae7758ba0b.png)
> 编译出来后就是这个样子,正在收集数据...
> oaf是加载的,
> 
> root@OpenWrt:~# lsmod |grep oaf
> oaf 49152 0

官方master分支下没问题。。。

**Comment by wlshdjj** [comment]
luci 1.x的不能使用，大家散了吧。
