### ISSUE TITLE
更新到最新版本后不能显示用户也不显示访问记录！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [destan19/OpenAppFilter#95]
![image](https://user-images.githubusercontent.com/45259624/109827447-b172ad80-7c76-11eb-85d5-c61f954398b7.png)

**Comment by zxlhhyccc** [comment]
暂时回退到旧版去算了。新版还是有点bug。。。

**Comment by destan19** [comment]
不会马上显示，统计用户需要等上报

**Comment by zxlhhyccc** [comment]
> 不会马上显示，统计用户需要等上报

从昨晚到现在，统计用户等均还没显示，我用的是官方master分子。。。。

**Comment by wlshdjj** [comment]
好歹你还能看到luci。。。
要不要MAC都无所谓，能用就行

**Comment by zxlhhyccc** [comment]
> 好歹你还能看到luci。。。
> 要不要MAC都无所谓，能用就行

新版很漂亮的，功能增加了很多。。。

**Comment by keeno1982** [comment]
我也是看不到用户，之前重启后一会儿就会出来，一天多了没显示应该是有问题
![Uploading 003.png…]()

**Comment by secretandanon** [comment]
看这个 https://github.com/destan19/OpenAppFilter/issues/102
