### ISSUE TITLE
iptables-mod-fullconenat也要关掉吗

### ISSUE THREAD

**Issue by lxwq** [destan19/OpenAppFilter#98]
![image](https://user-images.githubusercontent.com/51162826/110225895-ad6bb780-7f24-11eb-8b3b-61c99c6673dd.png)
但这个组件不知道要怎么取消,和别的有依赖关系,

**Comment by wlshdjj** [comment]
不用取消，你只要不开启就行

**Comment by lxwq** [comment]
> 不用取消，你只要不开启就行

搞了很久,终于明白是firewall防火墙依赖它,可是要关掉防火墙工具吗?
或者是我搞错了,

**Comment by lxwq** [comment]
现在编译出来,运行是这个样子,
![image](https://user-images.githubusercontent.com/51162826/110423187-94f1cd80-80db-11eb-9d57-bc223b9c4129.png)
if string.match(fullcone, "1")  or string.match(bbr, "1") or string.match(flow_offloading, "1") then
    um.value="运行环境检测失败，请先关闭ACC加速模块!"
这里面bbr和flow_offloading都没有编译上,只有kmod-ipt-fullconenat和iptables-mod-fullconenat因为防火墙依赖取消不掉,

**Comment by lxwq** [comment]
找不到哪的问题,换了lienol的源,防火墙选上编译,运行环境检测正常,

**Comment by chentengming** [comment]
@lxwq 请问你换了lienol的源，是哪个源？

**Comment by chentengming** [comment]
lienol的源也有这个问题吧 @lxwq 
local fullcone=SYS.exec("uci get firewall.@defaults[0].fullcone");
